### ISSUE TITLE
error that say : To install it, you can run: npm install --save fs  

### ISSUE THREAD

**Issue by yevpt** [ReAlign/markdown-it-copy#2]
ERROR  Failed to compile with 1 errors                                                                                                friendly-errors 16:47:26

This dependency was not found:                                                                                                         friendly-errors 16:47:26
                                                                                                                                       friendly-errors 16:47:26
* fs in ./node_modules/markdown-it-copy/index.js                                                                                       friendly-errors 16:47:26
                                                                                                                                       friendly-errors 16:47:26
To install it, you can run: npm install --save fs

**Comment by ReAlign** [comment]
Maybe you need check your development environment of node.js

**Comment by ReAlign** [comment]
If you need run it in browser, maybe you can look at the [#issue](https://github.com/ReAlign/markdown-it-copy/issues/3).
