### ISSUE TITLE
I found fs.readfilesync is no defind in Vue

### ISSUE THREAD

**Issue by tangzui** [ReAlign/markdown-it-copy#3]
I found fs.readfilesync is no defind in Vue
![image](https://user-images.githubusercontent.com/52860271/79638573-ab87f100-81b8-11ea-85cb-a9b8e16eb830.png)

**Comment by ReAlign** [comment]
Maybe you need check your development environment of node.js

**Comment by tangzui** [comment]
I have a feeling that this plugin is only applicable to the server side. I tried to directly assign the btnCode variable to the contents of code.js and found that it works.In addition, I would like to ask if I can fork and modify the release of the repository as NPM package

**Comment by ReAlign** [comment]
This plug-in was originally for node, not for browser. I will update it later to support browser. Of course, contributions to PR are also welcome.

**Comment by ReAlign** [comment]
Oh, markdown-it-plugin may only run on the node.js, it need `md.renderer.rules.code_block` and `md.renderer.rules.fence`, in browser, don't exist them.

**Comment by ReAlign** [comment]
Maybe you can show me your code-scene, such as codepen, or you git-repository.

**Comment by CaledoniaProject** [comment]
你为啥不用 import 去导入，非要读文件呢
